### ISSUE TITLE
Proglem with tagName property in latest netteForms.js

### ISSUE THREAD

**Issue by martinsifra** [nette/nette#1523] opened 2015-02-19 02:07 UTC
With latest (2.3.0 RC) netteForms.js a get this error „Cannot read property "tagName" of undefined“ with this call stack:

Nette.getValue:47
Nette.getEffectiveValue:91
Nette.toggleControl:413
Nette.toggleForm:398
Nette.initForm:504

It's only on manually rendered form, however the previous version without tagName property works fine. Of course i use macros {form …} or {input …} insted of HTML tags directly.

PS: Sorry, this shoul be in nette\forms repo.

**Comment by Majkl578** [comment] 2015-02-19 03:56
Duplicate of https://github.com/nette/forms/pull/63.

**Comment by milo** [comment] 2015-02-19 11:40
Closed by https://github.com/hranicka/forms/commit/ddf37d21dc9b65885d0a0e1095431a554ad5f1b8

**Closed by milo** 2015-02-19 11:40 UTC
